// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.225
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace GenieClient.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("GenieClient.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        internal static Bitmap accessories_text_editor
        {
            get
            {
                var obj = ResourceManager.GetObject("accessories_text_editor", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap applications_graphics
        {
            get
            {
                var obj = ResourceManager.GetObject("applications_graphics", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap control_edit
        {
            get
            {
                var obj = ResourceManager.GetObject("control_edit", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap control_pause
        {
            get
            {
                var obj = ResourceManager.GetObject("control_pause", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap control_play
        {
            get
            {
                var obj = ResourceManager.GetObject("control_play", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap control_stop
        {
            get
            {
                var obj = ResourceManager.GetObject("control_stop", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap dialog_warning
        {
            get
            {
                var obj = ResourceManager.GetObject("dialog_warning", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap document_new
        {
            get
            {
                var obj = ResourceManager.GetObject("document_new", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap document_open
        {
            get
            {
                var obj = ResourceManager.GetObject("document_open", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap document_save
        {
            get
            {
                var obj = ResourceManager.GetObject("document_save", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap document_save_as
        {
            get
            {
                var obj = ResourceManager.GetObject("document_save_as", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap edit_clear
        {
            get
            {
                var obj = ResourceManager.GetObject("edit_clear", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap edit_find
        {
            get
            {
                var obj = ResourceManager.GetObject("edit_find", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap folder_open
        {
            get
            {
                var obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap font_x_generic
        {
            get
            {
                var obj = ResourceManager.GetObject("font_x_generic", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap list_add
        {
            get
            {
                var obj = ResourceManager.GetObject("list_add", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap list_remove
        {
            get
            {
                var obj = ResourceManager.GetObject("list_remove", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap network_offline
        {
            get
            {
                var obj = ResourceManager.GetObject("network_offline", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap network_transmit
        {
            get
            {
                var obj = ResourceManager.GetObject("network_transmit", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap preferences_desktop_locale
        {
            get
            {
                var obj = ResourceManager.GetObject("preferences_desktop_locale", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap text_x_script
        {
            get
            {
                var obj = ResourceManager.GetObject("text_x_script", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap user_trash
        {
            get
            {
                var obj = ResourceManager.GetObject("user_trash", resourceCulture);
                return (Bitmap)obj;
            }
        }

        internal static Bitmap view_refresh
        {
            get
            {
                var obj = ResourceManager.GetObject("view_refresh", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}